### ISSUE TITLE
Missing container registry in CSV

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/web-ui-operator#59]
In 0.3, the web-ui csv generation code creates `image: kubevirt/kubevirt-web-ui-operator:latest` when it should be `image: quay.io/kubevirt/kubevirt-web-ui-operator:latest`.

**Comment by mareklibra** [comment]
The issue was expected to be resolved within https://github.com/kubevirt/hyperconverged-cluster-operator/pull/49 or https://github.com/kubevirt/hyperconverged-cluster-operator/pull/24 , but merged without responding the stated question.

The `GetDeployment()` method needs to be provided with the `registry` value within https://github.com/kubevirt/hyperconverged-cluster-operator, so the resulting CSV will contain proper image name.
